#!/bin/bash
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of Flight GL.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight GL is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight GL. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight GL, please visit:
# https://github.com/openflighthpc/flight-gl
#==============================================================================
if [ "$1" == "${FLIGHTGL_GPU}" ]; then
  echo "${FLIGHT_PROGRAM_NAME:-gl}: prevented kill of active GLX session; try 'stop' instead" 1>&2
  exit 1
fi

FLIGHTGL_CACHE_DIR="$HOME/.cache/flight/flightgl"
HOSTNAME="$(hostname -s)"

if [ -f "${FLIGHTGL_CACHE_DIR}"/${HOSTNAME}.gpu${1}.vars ]; then
  . "${FLIGHTGL_CACHE_DIR}"/${HOSTNAME}.gpu${1}.vars
  if [ -d /proc/$FLIGHTGL_PID ]; then
    kill ${FLIGHTGL_PID}
    echo "${FLIGHT_PROGRAM_NAME:-gl}: killed GLX session for GPU ${1}"
  else
    echo "${FLIGHT_PROGRAM_NAME:-gl}: unable to find active GLX session for GPU ${1}"
    exit 1
  fi
else
  echo "${FLIGHT_PROGRAM_NAME:-gl}: unable to find active GLX session for GPU ${1}"
  exit 1
fi
