#!/bin/bash
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of Flight GL.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight GL is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight GL. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight GL, please visit:
# https://github.com/openflighthpc/flight-gl
#==============================================================================
if [ -z "${FLIGHTGL_PID}" ]; then
  echo "${FLIGHT_PROGRAM_NAME:-gl}: no active GLX session" 1>&2
  exit 1
fi

if [ -d /proc/${FLIGHTGL_PID} ]; then
  kill ${FLIGHTGL_PID}
  echo "GLX session for GPU ${FLIGHTGL_GPU} (${FLIGHTGL_BUSID}) stopped" 1>&2
else
  echo "Cleaning inactive GLX session for GPU ${FLIGHTGL_GPU} (${FLIGHTGL_BUSID})" 1>&2
fi
cat <<EOF
trap - INT TERM EXIT
unset _flightgl_cleanup
unset VGL_DISPLAY
unset FLIGHTGL_ACTIVE
unset FLIGHTGL_DISPLAY
unset FLIGHTGL_GPU
unset FLIGHTGL_BUSID
unset FLIGHTGL_PID
EOF
