#!/bin/bash
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of Flight GL.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight GL is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight GL. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight GL, please visit:
# https://github.com/openflighthpc/flight-gl
#==============================================================================
if [ -z "$SUDO_USER" ]; then
  exit 1
fi
case $1 in
  chown)
    unset _TTY
    ttys="$(ps -o tty= $(pgrep Xorg) | xargs)"
    for a in $(seq 10 19); do
      if [[ " $ttys " != *" tty$a "* ]]; then
        _TTY=$a
        break
      fi
    done
    if [ "$_TTY" ]; then
      # Stop any gettys running on that TTY
      systemctl stop getty@tty$_TTY
      # Give ownership of /dev/ttyX to current user
      chown $SUDO_USER /dev/tty$_TTY
      echo $_TTY
    else
      exit 1
    fi
    ;;
  disown)
    if [ -c "/dev/tty$2" ]; then
      _OWNER="$(stat -c%U /dev/tty$2)"
      if [ "${_OWNER}" == "${SUDO_USER}" ]; then
        chown root /dev/tty$2
      fi
    fi
    ;;
  *)
    exit 1
    ;;
esac
